#!/bin/bash

curl -sL https://raw.githubusercontent.com/omersch381/arch-linux-install-ansible/master/arch_install_part2 > arch_install_part2.sh

chmod u+x arch_install_part2.sh

pacman -Syy reflector --noconfirm
timedatectl set-ntp true

parted --script /dev/sda mkpart primary fat32 1MiB 513MiB set 1 boot on mkpart primary ext4 513Mib 10GiB

mkfs.fat -F32 /dev/sda1
mkfs.ext4 /dev/sda2
mount /dev/sda1 /mnt

cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.bak
reflector --protocol http --protocol https --latest 20 --sort rate --save /etc/pacman.d/mirrorlist

mount /dev/sda2 /mnt
pacstrap /mnt base linux linux-firmware vim
genfstab -U /mnt >> /mnt/etc/fstab


cp arch_install_part2 /mnt/home/
arch-chroot /mnt sh /home/arch_install_part2

rm /mnt/home/arch_install_part2
echo 'Setup Complete!'
echo 'type "reboot" and remove installation media.'
