---
- name: Initial pacman configuration
  shell:
    cmd: "pacman -Syy --noconfirm"

- name: Ensure sudo package exists
  pacman:
    name: sudo
    state: latest

- name: Ensure wheel group exists
  group:
    name: wheel
    state: present

- name: Ensure the first non admin user exists and is in wheel group
  shell:
    cmd: useradd -m -g users -G wheel -s /bin/bash {{ hostname }}

- name: Ensure the first non admin user exists and is in wheel group
  user:
    name: "{{ hostname }}"
    update_password: always
    password: "{{ non_root_password | password_hash('sha512') }}"

- name: Ensure users in wheel group can run sudo commands
  lineinfile:
    path: /etc/sudoers
    line: "%wheel ALL=(ALL) ALL"
    validate: "visudo -cf %s"
