---
- name: Initial pacman configuration
  shell:
    cmd: "pacman -Syy --noconfirm"

- name: Ensure sudo package exists
  pacman:
    name: sudo
    state: latest

- name: Ensure wheel group exists
  group:
    name: wheel
    state: present

- name: Ensure the first non admin user exists and is in wheel group
  user:
    name: "{{ username }}"
    password: "{{ non_root_password }}"
    groups:
      - wheel
    append: yes
    shell: /usr/bin/zsh

- name: Ensure users in wheel group can run sudo commands
  lineinfile:
    path: /etc/sudoers
    line: "%wheel ALL=(ALL) ALL"
    validate: "visudo -cf %s"
