---
- name: Ensure git package is installed
  pacman:
    name: git
    state: latest

- name: Clone bare dotfiles repo
  vars:
    # converting from "https://github.com/username/repo_name" -> "https://username:token@github.com/username/repo_name"
    url_parts: "{{ dotfiles_git_repo | split('/') }}"
    extended_url: "https://{{ url_parts[3] }}:{{ github_token }}@{{ url_parts[2] }}/{{ url_parts[3] }}/{{ url_parts[4] }}"
  git:
    repo: "{{ extended_url }}" 
    bare: yes
    dest: "/home/{{ hostname }}/.config/dotfiles.git"

- name: Checkout bare dotfiles repo
  shell: "/usr/bin/git --git-dir=/home/{{ hostname }}/.config/dotfiles.git --work-tree=/home/{{ hostname }} checkout --force"

- name: Don't show untracked files on git status
  shell: "/usr/bin/git --git-dir=/home/{{ hostname }}/.config/dotfiles.git --work-tree=/home/{{ hostname }} config --local status.showUntrackedFiles no"

- name: Ensure cronie package is installed
  pacman:
    name: cronie
    state: latest

- name: Start and enable cronie.service
  service:
    name: cronie.service
    state: started
    enabled: true
