---
- name: Ensure Xorg packages are installed
  pacman:
    name:
      - xorg-xinit
      - xorg-server
      - i3-wm
      - rrdtool
      - xterm
      - feh
    state: latest

- name: Copy xinit sample file
  copy:
    src: /etc/X11/xinit/xinitrc
    dest: "{{ xinitrc_path }}"

- name: Copy xserverrc sample file
  copy:
    src: /etc/X11/xinit/xserverrc
    dest: /home/{{ hostname }}/.xserverrc

- name: Comment all irrelevant .xinitrc lines
  replace:
    path: "{{ xinitrc_path }}"
    regexp: '^(xterm)'
    replace: '# \1'

- name: Comment all irrelevant .xinitrc lines
  replace:
    path: "{{ xinitrc_path }}"
    regexp: '^(exec)'
    replace: '# \1'

- name: Ensure bash_profile starts Xorg
  blockinfile:
    path: /home/{{ hostname }}/.bash_profile
    block: |
      if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
              startx
      fi

- name: Ensure Xorg starts with i3
  lineinfile:
    path: "{{ xinitrc_path }}"
    insertafter: EOF
    line: 'exec i3'

- name: Ensure nerd-fonts-meslo is installed
  shell:
    cmd: "yay -S --needed --noconfirm nerd-fonts-meslo"
